iBroker/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

ibroker/urls.py
from django.urls import path


from . import views

app_name = 'ibroker'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('companies', views.CompaniesView.as_view(), name='companies'),
    path('companies/<slug:pk>/', views.CompanyDetail.as_view(), name='company_detail'),
    path('stocks/', views.StockListView.as_view(), name='stocks'),
    path('stocks/<slug:pk>', views.StockDetailView.as_view(), name='stock_detail'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('sell/', views.SellView.as_view(), name='sell'),
    path('history/', views.HistoryView.as_view(), name='history'),
    path('upload_quotes/', views.UploadQuoteView.as_view(), name='upload_quotes'),
    path('upload_stocks/', views.UploadStockCompanyView.as_view(), name='upload_stocks'),

]

market4fun/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView # new
from market4fun.views import HomePageView

urlpatterns = [
   path('users/',include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('ibroker/', include('ibroker.urls'), name='ibroker'), #Homepage é a homepage do app ibroker
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomePageView.as_view(), name='home'),
]

users/urls.py
# users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

iBroker/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

TOTAL_DIGITS = 15

# Create your models here.


class CustomUser(AbstractUser):

    def __str__(self):
        return self.email


class Address(models.Model):
    address_street = models.CharField(max_length=200)
    address_city = models.CharField(max_length=200)
    address_state = models.CharField(max_length=200)
    address_country = models.CharField(max_length=200)

class Company(models.Model):
    company_name = models.CharField(max_length=200)
    company_description = models.CharField(max_length=255)
    company_img_url = models.URLField() #TODO trocar para ImageField
    address = models.ForeignKey(Address,on_delete=models.CASCADE)

class Stock(models.Model):
    stock_code = models.CharField(max_length=50)
    stock_description = models.CharField(max_length=200)
    company = models.ForeignKey(Company,on_delete=models.CASCADE)

class Quote(models.Model):
    stock = models.ForeignKey(Stock,on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=TOTAL_DIGITS,decimal_places=2)
    quote_datetime = models.DateTimeField('Data da cotação')


class Order(models.Model):
    #BUY = 'B'
    #SELL = 'S'
    #ORDER_TYPES = [(BUY,"Compra"),(SELL,"Venda")]
    #order_type = models.CharField(max_length=1,choices=ORDER_TYPES,default=BUY)
    order_amount = models.IntegerField()
    order_price = models.DecimalField(max_digits=TOTAL_DIGITS,decimal_places=2)
    order_datetime = models.DateTimeField()
    order_user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)


#Todo criar esta view no banco de dados.

# class SimplifiedPortfolio (models.Model):
#     portfolio_stock = models.ForeignKey(Stock,on_delete=models.CASCADE)
#     portfolio_amount = models.IntegerField()
#     portfolio_mean_price = models.DecimalField(max_digits=TOTAL_DIGITS, decimal_places=2)
#     portfolio_current_price = models.DecimalField(max_digits=TOTAL_DIGITS, decimal_places=2)
#     portfolio_total_mean_price = models.DecimalField(max_digits=TOTAL_DIGITS,decimal_places=2)
#     portfolio_total_current_price = models.DecimalField(max_digits=TOTAL_DIGITS, decimal_places=2)
#     portfolio_pl = models.DecimalField(max_digits=TOTAL_DIGITS, decimal_places=2)
#
#     class Meta:
#         managed = False;
#         db_table='simplified_portfolio_view'

ibroker/forms.py
from django import forms
from ibroker.models import Stock,Quote,Order,UserHistory
from django.db.models import Sum,Count,F




class UploadQuotesFileForm(forms.Form):
    date= forms.DateTimeField()
    file = forms.FileField()

#Todo melhorar e colocar um jeito de o usuário ver o custo total da operação
#Acredito que deva ser feito no html, da pra fazer sem ajax se carregar todos os preços com uma lista ou algo assim
class OrderForm(forms.Form):
    stock = forms.ChoiceField(label='Stock: ')
    stock.widget.attrs.update({'class': 'form-control'})
    #price = forms.DecimalField(label='Price: ')
    qtd = forms.IntegerField(label='Quantidade',min_value=1)
    qtd.widget.attrs.update({'class': 'form-control'})

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(OrderForm, self).__init__(*args, **kwargs)

        stocks = Stock.objects.all()
        choices = [(stock.id, stock.stock_code) for stock in stocks]

        self.fields['stock'].choices = choices



    def clean(self):
        cleaned_data = super().clean()

        qtd = cleaned_data["qtd"]
        stockId = cleaned_data["stock"]

        stock = Stock.objects.get(pk=stockId)
        quote = Quote.objects.filter(stock=stock.id).order_by('-quote_datetime')[0]
        if not quote:
            raise forms.ValidationError(
                "There isn't a quote for {0}.".format(stock.stock_code)
            )

        if quote:
            if quote.price*qtd>UserHistory().get_amount_cash(self.user):
                raise forms.ValidationError(
                        "You don't have enough money to buy {0} of {1}.".format(qtd,stock.stock_code)
                    )

        return cleaned_data

class SellForm(forms.Form):
    stock = forms.ChoiceField(label='Stock: ')
    stock.widget.attrs.update({'class': 'form-control'})
    #price = forms.DecimalField(label='Price: ')
    qtd = forms.IntegerField(label='Quantidade: ',min_value=1)

    qtd.widget.attrs.update({'class': 'form-control'})
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(SellForm, self).__init__(*args, **kwargs)

        stocks = Stock.objects.all()
        choices = [(stock.id, stock.stock_code) for stock in stocks]

        self.fields['stock'].choices = choices


    def clean(self):
        cleaned_data = super().clean()

        qtdSell = cleaned_data["qtd"]

        stockId = cleaned_data["stock"]

        stock = Stock.objects.get(pk=stockId)
        quote = Quote.objects.filter(stock=stock.id).order_by('-quote_datetime')[0]
        current_qtd = Order.objects.filter(order_user = self.user).filter(order_stock_quote__stock = stock).aggregate(Sum('order_amount'))['order_amount__sum']


        if not quote:
            raise forms.ValidationError(
                "There isn't a quote for {0}.".format(stock.stock_code)
            )

        if quote:
            if not current_qtd:
                raise forms.ValidationError(
                        "Você não tem {0} no seu portfolio.".format(stock.stock_code)
                    )
            elif qtdSell>current_qtd:
                raise forms.ValidationError(
                        "Você tem apenas {0} ações de {1} no seu portfolio.".format(current_qtd,stock.stock_code)
                    )

        return cleaned_data

ibroker/views.py
from django.shortcuts import render,redirect
from django.shortcuts import Http404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView,ListView
from ibroker.models import Company, Stock, UserHistory
from ibroker.models import Quote,Order, PorfolioItem
from .forms import UploadQuotesFileForm,OrderForm,SellForm
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import datetime
import json
# Create your views here.

@method_decorator(login_required, name='dispatch')
class HomePageView(TemplateView):
    template_name = 'ibroker/home.html'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # ordersFromUser = Order.objects.filter(order_user = user)
        #
        # stocksDic = {}
        #
        # for order in ordersFromUser:
        #     quote = order.order_stock_quote
        #     stock = quote.stock
        #
        #     if not stock.id in stocksDic:
        #         invested_value= order.order_amount*quote.price
        #
        #
        #         current_price = Quote.objects.filter(stock=stock.id).order_by('-quote_datetime')[0].price
        #
        #         item = PorfolioItem(stock.stock_code,order.order_amount,invested_value,current_price)
        #
        #         stocksDic[stock.id] = item
        #
        #     else:
        #         stocksDic.get(stock.id).amount += order.order_amount
        #         stocksDic.get(stock.id).invested_value += order.order_amount * quote.price
        #         stocksDic.get(stock.id).current_value = stocksDic.get(stock.id).amount * stocksDic.get(stock.id).current_price
        #
        # total = 0
        # for stock in stocksDic:
        #     total += stock.invested_value

        dates = Quote.objects.values_list('quote_datetime').distinct().order_by('quote_datetime')


        dates = [d[0].date().__str__() for d in dates]
        perfs = [float(UserHistory().get_user_total_assets_value_date(user,d)) for d in dates]


        ctx = {
            'dates': json.dumps(dates),
            'perfs': json.dumps(perfs),
        }


        context['ctx'] = ctx
        context['user'] = self.request.user
        context['cash'] = UserHistory().get_amount_cash(user)
        context['total'] = UserHistory().get_user_total_assets_value_date(user,datetime.datetime.now())
        return context

#region Companhias
class CompaniesView(generic.ListView):
    template_name = 'ibroker/company/companies.html'
    context_object_name = 'company_list'

    def get_queryset(self):
        return Company.objects.all


class CompanyDetail(generic.DetailView):
    model = Company
    template_name = 'ibroker/company/detail.html'
#endregion






class UploadStockCompanyView(View):
    def get(self, request):
        user = request.user


        if not user.is_staff:
            return HttpResponse("Não pode")

        context = {'title': 'Upload Stocks File'}
        form = UploadQuotesFileForm()

        context['form'] = form
        return render(request, 'admin/admin.html', context)

    def post(self,request):
        context = {'title': 'Upload Stocks File'}

        user = request.user
        if not user.is_staff:
            return HttpResponse("Denied")

        form = UploadQuotesFileForm(request.POST, request.FILES)

        if form.is_valid():
            # Do your magic with the completed form data.
            date = form.cleaned_data['date']
            l = self.handle_upload_file(date, request.FILES['file'])

            # Let the user know that form was submitted.
            messages.success(request, 'Congrats, form submitted!')

            context['qtd'] = len(l)

            return render(request, 'admin/success.html', context)
        else:
            messages.error(
                request, 'Please correct the error below'
            )

        return render(request, 'admin/admin.html', context)



    def handle_upload_file(self,date,file):
        i=0
        list = []
        for line in file:
            if i==0:
                i+=1
                continue
            line = line.decode('utf-8', 'backslashreplace')
            cols = line.split("\t")

            stock_code = cols[0]
            stock_description = cols[1]
            name = cols[2]
            description = cols[3]
            img = cols[4]



            comp = Company(company_name= name,company_description=description,company_img_url=img)

            comp.save()

            stock = Stock(stock_code=stock_code,stock_description=stock_description,company=comp)
            stock.save()

            list.append(stock)

        return list




class UploadQuoteView(View):
    def get(self, request):
        user = request.user


        if not user.is_staff:
            return HttpResponse("Não pode")

        context = {'title': 'My Custom AdminForm'}
        form = UploadQuotesFileForm()

        context['form'] = form
        return render(request, 'admin/admin.html', context)

    def post(self,request):
        context = {'title': 'My Custom AdminForm'}

        user = request.user
        if not user.is_staff:
            return HttpResponse("Não pode")

        form = UploadQuotesFileForm(request.POST, request.FILES)



        if form.is_valid():
            # Do your magic with the completed form data.
            date = form.cleaned_data['date']
            l = self.handle_upload_file(date, request.FILES['file'])

            # Let the user know that form was submitted.
            messages.success(request, 'Congrats, form submitted!')


            context['qtd'] = len(l)

            return render(request, 'admin/success.html', context)
        else:
            messages.error(
                request, 'Please correct the error below'
            )

        return render(request, 'admin/admin.html', context)



    def handle_upload_file(self,date,file):
        stocks = Stock.objects
        i=0
        list = []
        for line in file:
            if i==0:
                i+=1
                continue
            line = line.decode('utf-8', 'backslashreplace')
            cols = line.split("\t")

            stock_code = cols[0]
            try:
                stock = stocks.get(stock_code=stock_code)
                quote_datetime = date

                try:
                    price = float(cols[2].replace(",","."))
                except:
                    price=0




                quote = Quote(stock=stock,price=price,quote_datetime=quote_datetime)
                quote.save()

            except:
                continue

        return list







def upload_file(request):
    if request.method=="POST":
        form = UploadQuotesFileForm(request.POST, request.FILES)

        if form.is_valid():
            #handle_upload_file(request.FILES['file'])
            return HttpResponse('Arquivo enviado com sucesso')
    else:
        form = UploadQuotesFileForm()
        return render(request,'upload.html',{'form':form})

@method_decorator(login_required, name='dispatch')
class OrderView(View):
    def get(self,request):
        user = request.user

        form = OrderForm(user=user)

        cash = UserHistory().get_amount_cash(user)
        return render(request, 'ibroker/order/order.html', {'form':form,'cash':cash})

    def post(self,request):
        user = request.user

        #Aqui a mágica acontece
        form = OrderForm(request.POST,user=user)

        if(form.is_valid()):
            try:
                qtd = form.cleaned_data['qtd'];
                stockId = form.cleaned_data['stock']
                stock = Stock.objects.get(pk=stockId)
                quote = Quote.objects.filter(stock = stock.id).order_by('-quote_datetime')[0]


                now = datetime.datetime.now()

                newOrder = Order(order_amount=qtd,order_stock_quote=quote,order_datetime=now,order_user=user)
                newOrder.save()

                total = quote.price*qtd
                user.cash=user.cash-total
                user.save()


                messages.success(request,"Ordem executada com sucesso")

                return HttpResponseRedirect(reverse("ibroker:portfolio"))
            except:
                raise Http404("Erro ao executar ordem.")

        cash = UserHistory().get_amount_cash(user)

        return render(request, 'ibroker/order/order.html', {'form':form,'cash':cash})



# Visualização da carteira do usuario - possibilidade de vender
@login_required
def portfolio(request):
    user = request.user
    ctx = {}

    #
    # ctx = Order.objects.raw(''' SELECT t3.stock_code,
    # sum(t1.order_amount) as amount,  sum(t1.order_amount*t2.price) as spent
    # FROM ibroker_order as t1
    # JOIN ibroker_quote as t2
    # ON t1.order_stock_quote_id=t2.id
    # JOIN ibroker_stock as t3 ON t2.stock_id=t3.id group by t3.id ''')

    ordersFromUser = Order.objects.filter(order_user = user)


    stocksDic = {}

    for order in ordersFromUser:
        quote = order.order_stock_quote
        stock = quote.stock

        if not stock.id in stocksDic:
            invested_value= order.order_amount*quote.price


            current_price = Quote.objects.filter(stock=stock.id).order_by('-quote_datetime')[0].price

            item = PorfolioItem(stock.stock_code,order.order_amount,invested_value,current_price)

            stocksDic[stock.id] = item

        else:
            stocksDic.get(stock.id).amount += order.order_amount
            stocksDic.get(stock.id).invested_value += order.order_amount * quote.price

ibroker/templates/ibroker/base.html
{% load static %}
<!-- templates/home.html -->
{% if user.is_authenticated %}

<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Market4Fun</title>

        <!-- Custom fonts for this template-->
        <link href={% static 'vendor/fontawesome-free/css/all.min.css' %} rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href={% static 'css/sb-admin-2.min.css' %} rel="stylesheet">

    </head>

    <body id="page-top">

        <!-- Page Wrapper -->
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home' %}">
                    <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-laugh-wink"></i>
                    </div>
                    <div class="sidebar-brand-text mx-3">Market4Fun</div>
                </a>

                <!-- Divider -->
                <hr class="sidebar-divider my-0">

                <!-- Nav Item - Dashboard -->
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ibroker:home' %}">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span></a>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Interface
                </div>

                <!-- Nav Item - Pages Collapse Menu -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ibroker:portfolio' %}">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Portfolio</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ibroker:companies' %}">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Empresas</span></a>
                </li>

                <hr class="sidebar-divider">
                <!-- Heading -->
                <div class="sidebar-heading">
                    Operações
                </div>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ibroker:stocks' %}">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Cotações</span></a>
                </li>
                <!-- Nav Item - Utilities Collapse Menu -->
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
                        <i class="fas fa-fw fa-wrench"></i>
                        <span>Ordens</span>
                    </a>
                    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" href="{% url 'ibroker:order'%}">Compra</a>
                            <a class="collapse-item" href="{% url 'ibroker:sell'%}">Venda</a>
                        </div>
                    </div>
                </li>

                <!-- Divider -->
            </ul>
            <!-- End of Sidebar -->

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    <!-- Topbar -->
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                        <!-- Sidebar Toggle (Topbar) -->
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>


                        <!-- Topbar Navbar -->
                        <ul class="navbar-nav ml-auto">

                            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                            <li class="nav-item dropdown no-arrow d-sm-none">
                                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-search fa-fw"></i>
                                </a>
                                <!-- Dropdown - Messages -->
                                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                                    <form class="form-inline mr-auto w-100 navbar-search">
                                        <div class="input-group">
                                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                                            <div class="input-group-append">
                                                <button class="btn btn-primary" type="button">
                                                    <i class="fas fa-search fa-sm"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </li>

                            <div class="topbar-divider d-none d-sm-block"></div>

                            <!-- Nav Item - User Information -->
                            <li class="mr-auto ml-md-2 my-2 no-arrow " href="#" data-toggle="modal" data-target="#logoutModal">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><a class="btn btn-primary" href="#">Logout</a></span>
                            </li>

                        </ul>

                    </nav>
                    <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">


            {% block content %}

            {% endblock %}


        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; market4fun 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>


  <!-- Bootstrap core JavaScript-->
  <script src={% static 'vendor/jquery/jquery.min.js' %}></script>
  <script src={% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}></script>

  <!-- Core plugin JavaScript-->
  <script src={% static 'vendor/jquery-easing/jquery.easing.min.js' %}></script>

  <!-- Custom scripts for all pages-->
  <script src={% static 'js/sb-admin-2.min.js' %}></script>

  <!-- Page level plugins -->
  <script src={% static 'vendor/chart.js/Chart.min.js' %}></script>

  <!-- Page level custom scripts -->
  <script src={% static 'js/demo/chart-area-demo.js' %}></script>
  <script src={% static 'js/demo/chart-pie-demo.js' %}></script>

    {% block scripts %}
    {% endblock %}
</body>

</html>
{% else %}
<p><a href="{% url 'signup' %}">Sign Up</a></p>
<p><a href="{% url 'login' %}">Log In </a></p>
{% endif %}

ibroker/templates/ibroker/portfolio.html
{% extends "ibroker/base.html" %}

{% block content %}

  <h1 class="h3 mb-2 text-gray-800">Portfolio</h1>

<div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Quantia Disponível</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">R${{cash}}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
     <!-- Earnings (Monthly) Card Example -->
                            <div class="col-xl-4 col-md-6 mb-4">
                                <div class="card border-left-success shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Patrimônio Total Atual</div>
                                                <div class="h5 mb-0 font-weight-bold text-gray-800">R$ {{total}}</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
</div>


{% if messages %}
<ul class="messages">
    {% for message in messages %}
<div class="col-lg-6 mb-4">
                  <div class="card bg-info text-white shadow">
                    <div class="card-body">
                        <p {% if message.tags %} class="mb-4"{% endif %} >{{ message }}</p>
                    </div>
                  </div>
                </div>
    {% endfor %}
</ul>

{% endif %}



          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Ativos</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Ação</th>
                      <th>Quantidade</th>
                      <th>Valor Investido</th>
                      <th>Preço Atual</th>
                      <th>Valor Total Atual</th>
                      <th>Vender</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Ação</th>
                      <th>Quantidade</th>
                      <th>Valor Investido</th>
                      <th>Preço Atual</th>
                      <th>Valor Total Atual</th>
                      <th>Vender</th>
                    </tr>
                  </tfoot>
                  <tbody>

                {% if dic %}
                    {% for key,item in dic.items %}

                    {% if item.amount > 0 %}
                    <tr>
                        <td>{{item.stock_code}}</td>
                        <td>{{item.amount}}</td>
                        <td>{{item.invested_value}}</td>
                        <td>{{item.current_price}}</td>
                        <td>{{item.current_value}}</td>
                        <td><a href="{% url 'ibroker:sell' %}"> Vender </a></td>
                    </tr>

    {% endif %}

    {% endfor %}

{% endif %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>
{% endblock %}

ibroker/templates/ibroker/quotes.html
<h1>Cotações</h1>
{% if quotes %}
    <ul>
    {% for stock in stocks %}
        <li><a href="{% url 'ibroker:stock_detail' stock.id %}">{{ stock.stock_code }} - {{ stock.stock_description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No stocks are available.</p>
{% endif %}